## I DON'T KNOW HOW TO USE THIS YET.  So far only output I see is 
## "Client sent an HTTP request to an HTTPS server." at http://192.168.0.10:6443/



# Create a Deployment:
# kubectl apply -f https://k8s.io/examples/controllers/nginx-deployment.yaml

# Check if deployment was created:
# kubectl get deployments

# Check Deployment rollout status:
# kubectl rollout status deployment/nginx-deployment


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

# Sources
# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/

# ubuntu@dom-pi:~$ kubectl cluster-info
# Kubernetes control plane is running at https://192.168.0.10:6443
# CoreDNS is running at https://192.168.0.10:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

# To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
# ubuntu@dom-pi:~$ 

# kubectl config view

# history
# 287  kubectl get nodes
#   288  clear
#   289  kubectl apply -f https://k8s.io/examples/controllers/nginx-deployment.yaml
#   290  kubectl get deployments
#   291  kubectl rollout status deployment/nginx-deployment
#   292  kubectl get pods --show-labels
#   293  kubectl get pods
#   294  kubectl describe deployment
#   295  kubectl get nodes
#   296  docker ps | grep kube-apiserver
#   297  cat $HOME/.cube/config
#   298  cat \$HOME/.kube/config 
#   299  cd $HOME/.kube/config
#   300  cd /\$HOME/.kube/config
#   301  echo $HOME
#   302  pwd
#   303  ls -la
#   304  cd .kube/
#   305  ls
#   306  cat config
#   307  cat /etc/kubernetes/admin.conf
#   308  sudo cat /etc/kubernetes/admin.conf
#   309  kubectl cluster-info
#   310  sudo chown $(id -u):$(id -g) $HOME/.kube/config
#   311  cd
#   312  kubectl cluster-info
#   313  kubectl config view
#   314  sudo kubectl cluster-info
#   315  history

# Other ppl struggling
# https://discuss.kubernetes.io/t/the-connection-to-the-server-localhost-8080-was-refused-did-you-specify-the-right-host-or-port/1464/7